dbConfig:
  - connectionName: devDb
    host: 192.168.10.110
    port: 3307
    userName: root
    password: Huawei123
  - connectionName: testDb
    host: 192.168.10.110
    port: 3307
    userName: root
    password: Huawei123
dumpConfig:
  - dbName: oyetalk-pay
    tableName: t_order
    whereOperation: 1=1
    backFilePath: /home/tp/
    s3BackDir: oyetalk-status/
    s3Bucket: oyetalk-test
    autoDelete: true
    deleteLimit: 1
    dumpUseDb: devDb
    deleteUseDb: testDb
  - dbName: oyetalk-account
    tableName: t_operation
    whereOperation: 1=1
    backFilePath: /home/tp/
    s3BackDir: oyetalk-status/
    s3Bucket: oyetalk-test
    autoDelete: true
    deleteLimit: 1
    dumpUseDb: devDb
    deleteUseDb: testDb

