dbConfig:
  - connectionName: devDb
    host: 192.168.1.124
    port: 3307
    userName: root
    password: 123456
  - connectionName: testDb
    host: 192.168.1.124
    port: 3307
    userName: root
    password: 123456
dumpConfig:
  - dbName: test-pay
    tableName: t_order
    whereOperation: create_time>'2021-04-10' and create_time<'2021-04-13'
    backFilePath: /home/aaa/
    s3BackDir: test-status/
    s3Bucket: test-test
    autoDelete: true
    deleteLimit: 1
    dumpUseDb: devDb
    deleteUseDb: testDb

